@startuml

class Модель {
    id: integer
}

class Представление {
    id: integer
}

class Контроллер {
    id: integer
}

class Пользователь {
    id: integer
    имя: string
    адрес: integer
    хеш: integer
}

class Стол {
    id: integer
    количество_мест: integer
    id_половины: integer
    id_изображения: integer
    комментарий: string
    цена: integer
}

class Зал {
    id: integer
    тип_названия: string
}

class Изображение {
    id: integer
    байт: integer
}

class Заказ {
    id: integer
    конец_времени: time
    начало_даты_времени: timestamp
    id_стола: integer
    id_пользователя: integer
    id_коэффициента: integer
}

class Коэффициент {
    id: integer
    коэффициент: integer
}

Модель "1" -- "0..*" Пользователь
Модель "1" -- "0..*" Стол
Модель "1" -- "0..*" Зал
Модель "1" -- "0..*" Изображение
Модель "1" -- "0..*" Заказ
Модель "1" -- "0..*" Коэффициент

Представление "1" -- "0..*" Пользователь
Представление "1" -- "0..*" Стол
Представление "1" -- "0..*" Зал
Представление "1" -- "0..*" Изображение
Представление "1" -- "0..*" Заказ
Представление "1" -- "0..*" Коэффициент

Контроллер "1" -- "0..*" Пользователь
Контроллер "1" -- "0..*" Стол
Контроллер "1" -- "0..*" Зал
Контроллер "1" -- "0..*" Изображение
Контроллер "1" -- "0..*" Заказ
Контроллер "1" -- "0..*" Коэффициент

@enduml
